# Configurações globais aplicadas a todo o arquivo de configuração do Prometheus.
global:
  # Intervalo de raspagem global. Define com que frequência o Prometheus coleta métricas.
  scrape_interval: 5s
  # Intervalo de avaliação global. Define com que frequência as regras de alerta são avaliadas.
  evaluation_interval: 10s
  # Lista de arquivos de regras a serem carregados.
rule_files:
  - rules.yml

# Configurações de alerta.
alerting:
  # Lista de configurações de Alertmanager.
  alertmanagers:
    - static_configs:
      # Configurações estáticas para o Alertmanager, definindo os alvos para envio de alertas.
      - targets:
        - localhost:9093

# Configurações de raspagem (scrape).
scrape_configs:
  # Configurações para o job chamado 'prometheus'.
  - job_name: prometheus
    # Configuração estática para definir os alvos (targets) para raspagem.
    static_configs:
      - targets: ["localhost:9090"]

  # Configurações para o job chamado 'simple_server'.
  - job_name: simple_server
    # Configuração estática para definir os alvos (targets) para raspagem.
    static_configs:
      - targets: ["localhost:8090"]